# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

L0PoissonApproximate <- function(y, l, w) {
    .Call(`_l0approximatorR_L0PoissonApproximate`, y, l, w)
}

L0GaussianApproximate <- function(y, l, w) {
    .Call(`_l0approximatorR_L0GaussianApproximate`, y, l, w)
}

L0ExponentialApproximate <- function(y, l, w) {
    .Call(`_l0approximatorR_L0ExponentialApproximate`, y, l, w)
}

L0PoissonApproximateN <- function(y, N, w) {
    .Call(`_l0approximatorR_L0PoissonApproximateN`, y, N, w)
}

L0GaussianApproximateN <- function(y, N, w) {
    .Call(`_l0approximatorR_L0GaussianApproximateN`, y, N, w)
}

L0ExponentialApproximateN <- function(y, N, w) {
    .Call(`_l0approximatorR_L0ExponentialApproximateN`, y, N, w)
}

